FROM node:alpine

WORKDIR /usr/app

COPY ./package.json ./

RUN npm i

COPY ./ ./

CMD ["npm","run","devtsc"]


#efe297aad7ff

#docker run -it -p '3000:3000'  -v /usr/app(WORKDIR)/node_modules -v $(pwd):/usr/app(WORKDIR)   efe297aad7ff
